version: "3.8"

services:

  nginx_server:
    container_name: nginx-proxy-server-for-kubernetes
    image: nginx-proxy-server-for-kubernetes
    build: ./
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    restart: always

volumes:
  letsencrypt:
    name: letsencrypt
